##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: CrediYaSolicitud
  devtools:
    add-properties: false
  profiles:
    include:
  flyway:
    url: "jdbc:mysql://localhost:3307/solicitudes_db"
    user: "jpriva"
    password: "pass12345"
    locations: "classpath:db/migration"
    enabled: true

adapters:
  r2dbc:
    host: "localhost"
    port: 3307
    database: "solicitudes_db"
    username: "jpriva"
    password: "pass12345"