server:
  port: 8080
spring:
  application:
    name: "CrediYaSolicitud"
  devtools:
    add-properties: false
  profiles:
    include: null
  flyway:
    url: "jdbc:mysql://localhost:3307/solicitudes_db"
    user: "jpriva"
    password: "pass12345"
    locations: "classpath:db/migration"
    enabled: true
adapters:
  r2dbc:
    host: "localhost"
    port: 3307
    database: "solicitudes_db"
    username: "jpriva"
    password: "pass12345"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
