server:
  port: 8082
spring:
  application:
    name: "CrediYaSolicitud"
  devtools:
    add-properties: false
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  flyway:
    url: "jdbc:mysql://${SPRING_R2DBC_HOST:localhost}:${SPRING_R2DBC_PORT:3307}/${SPRING_R2DBC_DB:solicitudes_db}"
    user: "${SPRING_DB_USERNAME:jpriva}"
    password: "${SPRING_DB_PASSWORD}"
    locations: "classpath:db/migration"
    enabled: true
  output:
    ansi:
      enabled: DETECT
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SECURITY_PUBLIC_KEY_URI}

adapters:
  r2dbc:
    host: "${SPRING_R2DBC_HOST:localhost}"
    port: "${SPRING_R2DBC_PORT:3307}"
    database: "${SPRING_R2DBC_DB:solicitudes_db}"
    username: "${SPRING_DB_USERNAME:jpriva}"
    password: "${SPRING_DB_PASSWORD}"
  restconsumer:
    url: "${ADAPTERS_RESTCONSUMER_URL:http://localhost:8081}"
    timeout: 5000
    pathUsersByEmails: "/api/v1/busquedas/emails"
    pathUserByEmail: "/api/v1/busquedas/email/"
    pathUsersByFilter: "/api/v1/busquedas/filtro"
  sqs:
    region: "${ADAPTERS_SQS_REGION:us-east-1}"
    endpoint: "${ADAPTERS_SQS_ENDPOINT_OVERRIDE:}"
    queues:
      state-change: "${STATE_SQS_ENDPOINT_OVERRIDE:}"
      debt-capacity: "${DEBT_SQS_ENDPOINT_OVERRIDE:}"
      metric: "${METRIC_SQS_ENDPOINT_OVERRIDE:}"
    metrics:
      quantity: "${DYNAMO_QUANTITY_METRIC:quantity}"
      amount: "${DYNAMO_AMOUNT_METRIC:amount}"
management:
  endpoints:
    web:
      base-path: "/solicitude/actuator"
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8082}"
springdoc:
  api-docs:
    info:
      title: "Crediya Loan Application API Microservice"
      version: "1.0.0"
      description: "This is the API for Crediya Loan Application Microservice"
    path: /solicitude/api-docs
  swagger-ui:
    path: /solicitude/swagger-ui.html
security:
  jwt:
    callback-secret: "${JWT_SECRET:}"
    expiration: 3600
