spring:
  flyway:
    url: "jdbc:mysql://${SPRING_R2DBC_HOST:localhost}:${SPRING_R2DBC_PORT:3307}/${SPRING_R2DBC_DB:solicitudes_db}"
    user: "${SPRING_DB_USERNAME:jpriva}"
    password: "${SPRING_DB_PASSWORD:pass12345}"

adapters:
  sqs:
    queues:
      state-change: "https://sqs.us-east-1.amazonaws.com/096187159240/solicitude-approved-queue"
      debt-capacity: "https://sqs.us-east-1.amazonaws.com/096187159240/debt-capacity-queue"
      metric: "https://sqs.us-east-1.amazonaws.com/096187159240/solicitude-report-queue"
  r2dbc:
    host: "${SPRING_R2DBC_HOST:localhost}"
    port: "${SPRING_R2DBC_PORT:3307}"
    database: "${SPRING_R2DBC_DB:solicitudes_db}"
    username: "${SPRING_DB_USERNAME:jpriva}"
    password: "${SPRING_DB_PASSWORD:pass12345}"

security:
  jwt:
    secret: ${JWT_SECRET:iBdGbA8Dxowf12Zs7IYH91+KwKOg5yb39RGQv6pOWes=}