spring:
  flyway:
    url: "jdbc:mysql://${SPRING_R2DBC_HOST:localhost}:${SPRING_R2DBC_PORT:3307}/${SPRING_R2DBC_DB:solicitudes_db}"
    user: "${SPRING_DB_USERNAME:jpriva}"
    password: "${SPRING_DB_PASSWORD:pass12345}"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SECURITY_PUBLIC_KEY_URI:http://localhost:8081/.well-known/jwks.json}

adapters:
  sqs:
    queues:
      state-change: "${ADAPTERS_SQS_ENDPOINT_OVERRIDE:http://localhost:4566}/000000000000/solicitude-approved-queue"
      debt-capacity: "${ADAPTERS_SQS_ENDPOINT_OVERRIDE:http://localhost:4566}/000000000000/debt-capacity-queue"
      metric: "${ADAPTERS_SQS_ENDPOINT_OVERRIDE:http://localhost:4566}/000000000000/solicitude-report-queue"
    endpoint: "${ADAPTERS_SQS_ENDPOINT_OVERRIDE:http://localhost:4566}"
  r2dbc:
    host: "${SPRING_R2DBC_HOST:localhost}"
    port: "${SPRING_R2DBC_PORT:3307}"
    database: "${SPRING_R2DBC_DB:solicitudes_db}"
    username: "${SPRING_DB_USERNAME:jpriva}"
    password: "${SPRING_DB_PASSWORD:pass12345}"

security:
  jwt:
    callback-secret: ${JWT_SECRET:iBdGbA8Dxowf12Zs7IYH91+KwKOg5yb39RGQv6pOWes=}

logging:
  level:
    co.com.pragma: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
